### PR TITLE
Release 1.0.1

### PR DESCRIPTION
**Pull request by ajlanghorn**
- Tightens dependency on vcloud-tools-tester
- Updates integration test details in README

### CODE REVIEW

**Comment by ajlanghorn** [comment]
This relies on #156.

**Comment by ajlanghorn** [comment]
Closing to update Gemspec further.

**Comment by ajlanghorn** [comment]
Further Gemspec updates to come in a separate PR.

**Comment by rjw1** [comment]
closing while we make another change to the gem spec.

**Pull request closed without merging**
