### PR TITLE
Add require json as this is required for ruby > 2.0.

### PR DESCRIPTION
**Pull request by noels**

### CODE REVIEW

**Comment by mattbostock** [comment]
Thanks for contributing @noels.

We run our tests against versions of Ruby [greater than 2.0](https://github.com/gds-operations/vcloud-core/blob/5e1a885122094447fb5f39265b98d47842bce059/.travis.yml#L6) but it doesn't seem to cause any issues; is there something about the version you are using?

Note that this has been reported previously:
https://github.com/gds-operations/vcloud-core/issues/163

**Comment by noels** [comment]
I tried the vcloud-launch command on ruby 2.2.2 and 2.1.5 and both versions of Ruby produced the same error about an undefined constant VCloud:Core::ConfigLoader:JSON.

**Comment by annashipman** [comment]
I think we should merge this even though we don't reproduce this error in our tests. The mystery here is not why this solves the problem seen by @noels, @scarby and @rickard-von-essen, the mystery seems more to be how does this ever work?! I'm interested in the answer to that, but in the meantime it appears to be blocking people and this looks like a reasonable solution to their problem. What do you think @mattbostock?

**Comment by mattbostock** [comment]
@annashipman I'd rather not merge until we've identified the cause of the problem (which we should do as a priority). As-is, the commit message is inaccurate because we know the tests can pass in Ruby 2.1.2, for example.

I was able to reproduce the error under Ruby 2.2.2, so I've raised a PR to run the tests against that version:
https://github.com/gds-operations/vcloud-core/pull/171

I'll see if I can find what changed in later Ruby versions.

**Comment by mattbostock** [comment]
It looks like this issue occurs when using specific combinations of the gems that vCloud Core depends on. It seems that if one of the gems we depend on includes `require 'json'`, then the tests would pass. For example:

```ruby
matt➜govuk/vcloud-gems/vcloud-core(master✗)» pry
[1] pry(main)> defined? JSON
=> nil
[2] pry(main)> require 'mime/types'
=> true
[3] pry(main)> defined? JSON
=> "constant"
[4] pry(main)>
```

I have merged #164, which addresses the same issue. Thanks again for contributing this @noels.

I'll write up a more detailed explanation in #163.

**Comment by noels** [comment]
Just to let you know we lost another half an hour of someone's time because they ran into the exact same issue again before they came to ask why it wasn't working for them.

**Comment by mattbostock** [comment]
@noels: Did they getting it working by upgrading to the latest version?

**Comment by noels** [comment]
They are running:
vcloud-core (1.0.2)
vcloud-edge_gateway (1.5.0)
vcloud-launcher (1.0.0)
vcloud-net_launcher (1.0.0)
vcloud-tools-tester (1.0.0)
vcloud-walker (4.0.0)
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

They got it working by adding require 'json'

Has the version with the fix been released?  vcloud-tools was installed according to the instructions.

**Comment by mattbostock** [comment]
@noels Which tool in particular were they using?

**Comment by noels** [comment]
vcloud-edge-configure was showing the issue. They edited the file in this pr which didn't have the require 'json'

**Comment by mattbostock** [comment]
@noels Thanks for reporting this.

We need to publish [version 1.5.2](https://github.com/gds-operations/vcloud-edge_gateway/commit/1a01e77c708f904af99ae1bd1b1d386ca50e374b) of vCloud Edge Gateway, however we're currently blocked from doing so due to a bug in Fog which is causing our integration tests to fail. We've done some investigation, have a workaround for Fog and are aiming to raise a fix soon however other work is currently taking priority. We'll update this issue as soon as we have an update.

**Pull request closed without merging**
